### ISSUE TITLE
Bwrap troubles ?

### ISSUE THREAD

**Issue by fwn0** [ivan-hc/Amarok-appimage#1]
Hello Ivan,
I have problems with bwrap.
I tested your Amarok a Hypnotix appimages on Artix (systemd-free) and got this error message:
bwrap: Can't find source path /media: No such file or directory ....
Same errors with extracted images. How can I fix it ?

**Comment by ivan-hc** [comment]
> Hello Ivan,
I have problems with bwrap.
I tested your Amarok a Hypnotix appimages

All of us have this problem! They are EXPERIMENTAL and NOT FOR DAILY USE!

I have already wrote this in the README and the description.

You should not use them. I'm still trying to improve them commit by commit.

**Comment by ivan-hc** [comment]
> bwrap: Can't find source path /media: No such file or directory ....
Same errors with extracted images. How can I fix it ?

```
sudo mkdir /media
```

@fwn0  I wrote my Archimages to automatically mount /mnt and /media, that many distros have to mount external devices.

If you have not them, just create them. They are just directories.

**Comment by fwn0** [comment]
OK, just created the /media directory and the error message is gone. Amarok still gets error: /home/artix/Downloads/Amarok_2.9.71-5-archimage3.2-x86_64.AppImage 
amarok: Error loading shared libraries: libtag.so.1: cannot open the shared object file: No such file or directory.
I think that your appimage does not include some media libs.

**Comment by fwn0** [comment]
Just tested Hypnotix - it crash because:
MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/dri, suffix _dri)

**Comment by ivan-hc** [comment]
I know this too :(  : 
- Amarok requirest `libtag.so.1` while ArchLinux only provides `libtag.so` and `libtag.so.2`. If you see [my workflow runs](https://github.com/ivan-hc/Amarok-appimage/actions), those that are failed are based on both the AUR packages (amarok or amarok-git), while those that were completed are based on ChaoticAUR, that does not compile from source, and `libtag.so.x` cannot be compiled being Chaotic a repository of precompiled binaries from AUR;
- Hypnotix, like [Bottles](https://github.com/ivan-hc/Bottles-appimage)... but any other Archimage, [is based on JuNest, a container without access to the host's drivers](https://github.com/fsquillace/junest/issues/344). However, Hypnotix has another issue that is not strictly related to the MESA drivers (also [Chromium](https://github.com/ivan-hc/Chromium-Web-Browser-appimage) requires them, but I can watch 4K videos on YouTube normally)... and if you get the error for /usr/lib/dri/iris_dri.so I have an Nvidia, so I get the error about /usr/lib/dri/nvidia_dri.so. This is a known issue https://github.com/ivan-hc/Hypnotix-appimage#known-issue and I investigated about it, there seems to be a problem with pipewire or other services running in the background.


EDIT: about Amarok, if you can see my latest workflow runs all of them are based on the AUR package and both are broken. No way to going on.

**Comment by ivan-hc** [comment]
@fwn0 let open an issue on the https://github.com/ivan-hc/Hypnotix-appimage repository, I'm investigating on some interesting mountpoints to find.

**Comment by fwn0** [comment]
OK, let me check your other interesting portable media appimages; vlc, mpv, obs, handbrake and other progs.
I'm very busy at the moment and I don't have much time for testing. I'm also not very interested in JuNest (IMO runimage is more flexible and powerful) and also AppImages are not perfectly portable for me. IMO AppImage is the history (solid and nice), but I also like the future - DwarFS ;).

**Comment by ivan-hc** [comment]
> runimage

interesting... I was not aware about it. Great! I'll take a look to it.

In the meantime, I'll put all my researches on Hypnotix at https://github.com/ivan-hc/Hypnotix-appimage/issues/2 when you have time, take a look at this.
